// Generated by nuxi
/// <reference types="@nuxtjs/eslint-module" />
/// <reference types="@nuxtjs/device" />
/// <reference types="@nuxtjs/fontawesome" />
/// <reference types="bootstrap-vue" />
/// <reference types="@nuxtjs/axios" />
/// <reference types="@nuxtjs/sitemap" />
/// <reference types="@nuxt/components" />
/// <reference types="@nuxt/telemetry" />

export {}
